config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks }

  devise_scope :user do 
    get "welcome", to: "devise/sessions#new", as: :welcome
  end

  resources :locations 

  get "loading", to: "dashboard#loading"
  get "status", to: "dashboard#status"

  root to: "dashboard#index"
end

app/models/location.rb
require 'am_dash/locations/categories'

class Location < ActiveRecord::Base
  include AMDash::Locations::Categories

  validates_presence_of :address, :user_id, :category

  scope :home, -> { where(category: AMDash::Locations::Categories::LOCATION_CATEGORIES[:home]).first }
  scope :work, -> { where(category: AMDash::Locations::Categories::LOCATION_CATEGORIES[:work]).first }
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  has_many :locations, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def ensure_registration_complete
    unless current_user.locations.present?
      flash[:notice] = "Just one more thing..."
      redirect_to new_location_path
    end
  end

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to welcome_path
    end
  end

end

app/controllers/dashboard_controller.rb
require 'am_dash/am_dash'
require 'am_dash/worker'

class DashboardController < ApplicationController

  before_action :authenticate_user!, :ensure_registration_complete
  before_action :verify_user_data_present, only: [:index]

  def index
    @account_summary = JSON.parse(account_summary_store)
    @weather_forecast = JSON.parse(weather_store)
    @events = JSON.parse(events_store)
    @news_articles = JSON.parse(news_store)
  end

  def loading

  end

  def status
    render :json => (stored_data_present? ? 1 : 0)
  end

  private

  def verify_user_data_present
    unless stored_data_present?
      AMDash::Worker.enqueue(:download_and_store_user_data, current_user.id)
      redirect_to loading_path
    end
  end

  def stored_data_present?
    account_summary_store && weather_store && events_store && news_store
    #note that if API calls fails to download and store data, we'll at least have some object,
    #even if it's just an empty array or empty hash
  end

  def account_summary_store
    data_store("#{current_user.id}-account")
  end

  def weather_store
    data_store("#{current_user.id}-weather")
  end

  def events_store
    data_store("#{current_user.id}-events")
  end

  def news_store
    data_store("news")
  end

  def data_store(key)
    AMDash::Cache.read(key) 
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!

  def index
  end
end

app/controllers/locations_controller.rb
require 'am_dash/am_dash'

class LocationsController < ApplicationController

  before_filter :authenticate_user!

  def new
    @home = Location.new
    @work = Location.new
  end

  def create
    @home, @work = AMDash.create_location.execute(params[:home_address], params[:work_address], current_user.id)
    if !@home.errors.any? && !@work.errors.any?
      redirect_to root_url
    else
      flash[:error] = "Something went wrong. Please try again."
      render :new
    end
  end

end

app/controllers/omniauth_callbacks_controller.rb
require 'am_dash/am_dash'

class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    auth_data = request.env['omniauth.auth']
    @user = AMDash.find_or_create_from_google.execute(auth_data)
    if @user
       sign_in_and_redirect @user
    else
      flash[:error] = "Something went wrong. Please try again."
      redirect_to new_user_session
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


  def errors_for(model, attribute)
    if model.errors.messages[attribute].present?
      content_tag :span, :class => 'error_message' do
        model.errors[attribute].join(", ")
      end
    end
  end

  def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"   # Green
    when "error"
      "alert-danger"    # Red
    when "alert"
      "alert-warning"   # Yellow
    when "notice"
      "alert-info"      # Blue
    else
      flash_type.to_s
    end
  end

end

app/views/dashboard/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "map.js" %>
<% end %>

<div class="container">

  <div class="header text-center">
    <div class="row">
      <div class="col-lg-12">

        <h1>Good Morning, <%= @account_summary["first_name"] %> </h1>

      </div> <!-- /cols -->
    </div> <!-- /row -->
  </div> <!-- /header -->


  <div class="row">

    <!-- start left col -->
    <div class="col-lg-6">

      <section class="date">

        <div class="card">
          <h2> <%= Date.today.strftime("%A, %b %d, %Y") %> </h2>
        </div> <!-- /card -->

      </section>

      <section class="weather">
        <div class="card">
          <h2> Today's Forecast </h2>

          <div class="weather-forecast">

            <table class="table table-striped">
              <tr>

                <th>
                  Time
                </th>
                <th>
                  6:00
                </th>
                <th>
                  9:00
                </th>
                <th>
                  12:00
                </th>
                <th>
                  3:00
                </th>
                <th>
                  6:00
                </th>
                <th>
                  9:00
                </th>

              </tr>

              <tr>

                <td>
                  Temp
                </td>

                <% @weather_forecast.each do |forecast| %>

                  <td>
                    <%= forecast["temp"] ? forecast["temp"].to_i : "n/a" %> &deg;
                  </td>

                <% end %>

              </tr>

            </table>
          </div> <!-- /forecast -->

        </div> <!-- /card -->
      </section>

      <section class="news">
        <div class="card">
          <h2> Top News </h2>

          <% @news_articles.first(3).each do |news_article| %>
            <article>
              <h3>
                <%= news_article["headline"] %>
              </h3>

              <div class="article-summary">
                <p>
                <%= news_article["snippet"] %>
                </p>
                <p>
                <%= link_to "Read More", news_article["url"], target: "_blank" %>
                </p>
              </div>

            </article>

            <hr / >
          <% end %>

        </div> <!-- /card -->
      </section>

    </div> <!--/ left col -->


    <!-- start right col -->
    <div class="col-lg-6">


      <section class="events">

        <div class="card">
          <h2> Today's Events </h2>

          <ul class="text-center">

            <% if @events.any? %>

              <% @events.each do |event| %>

                <li>
                  <div class="row">

                    <span class="event-start"> 
                      <strong>
                        <%= event["start"] %>
                      </strong>
                    </span> 

                    <span class="event-description"> 
                      <%= event["name"] %>
                    </span> 

                  </div> 

                </li>

              <% end %>
            <% else %>
              <h4>
                No events currently on your Google calendar.
              </h4>
              <h5>
                Time to relax.
              </h5>
            <% end %>

          </ul>
        </div> <!-- /card -->

      </section>

      <section class="Traffic">
        <div class="card">
          <h2> Commute </h2>
          <h4> Green is Good... Red is Bad </h4>

          <div id="map" data-lat="<%= @account_summary["work_latitude"] %>" data-lon="<%= @account_summary["work_longitude"]%>" >
          </div>

        </div> <!-- /card -->
      </section>

    </div> <!--/ right col -->

  </div> <!-- /row -->

</div> <!-- /container -->

app/views/dashboard/loading.html.erb
  <div class="container">
    <div class="row well">

      <h1> Grabbing some fresh data for you. </h1>
      <h2> This will only take a moment... </h2>


    </div><!--/row -->
  </div><!--/ container -->



<script type="text/javascript">

var intervalId = setInterval(function() {
  $.get("<%= status_path %>", function(finished) {
    if (finished) {
      clearInterval(intervalId);
      document.location = "<%= root_path %>"
    };
  });
}, 1000);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">  
  <head>
    <title>AMDash</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <div class="row">
        <% flash.each do |key, value| %>
          <div class="alert <%= bootstrap_class_for(key) %> fade in text-center margin-top-one-em">
            <%= value %>
          </div><!-- /alert -->
        <% end %>
      </div> <!-- /row -->
    </div> <!-- /container -->

    <%= yield %>

    <% if user_signed_in? %>
      <footer class="footer">
        <div class="row">
          <p>
          <%= link_to "Log out", destroy_user_session_url, method: :delete, class: "btn btn-info btn-secondary" %>
          </p>

        </div> <!-- /row -->
      </footer>
    <% end %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= yield :javascript_includes %>
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['AM_DASH_GOOGLE_BROWSER_KEY'] %>&callback=AMDash.initMap">
    </script>


  </body>
</html>

app/views/locations/new.html.erb
<section class="add-locations">

  <div class="container">
    <div class="row">
      <div class="well text-center registration">

        <h2> Your Location </h2>

        <div class="form-explanation">

          In order to help you get your day off right, we need to know where you're starting off and where you're going.
        </div> <!-- /form-explanation -->

        <%= form_tag locations_path, method: :post do %>

          <div class="form-group">
            <%= text_area_tag :home_address, @home.address, placeholder: "Home Address", class: "form-control" %>
            <%= errors_for(@home, :address)  %>

          </div> <!-- /form-group -->
          <div class="form-group">
            <%= text_area_tag :work_address, @work.address, placeholder: "Work Address", class: "form-control" %>
            <%= errors_for(@work, :address)  %>
          </div> <!-- /form-group -->

          <%= submit_tag "Next", class: "btn btn-primary btn-lg" %>

        <% end %>

      </div> <!--well -->
    </div> <!-- /row -->
  </div> <!-- /container -->

</section>